apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
<<<<<<< HEAD
        image: 192.168.178.115:5000/mynginx:036c71fe0cb3f851e291a9e50b83d9316ce93f7c
=======
        image: mynginx:192.168.178.115:5000/mynginx:latest
>>>>>>> 38e21cb571e1f6bb93c31fa00c323da82926499d
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
