name: Build and Deploy Local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t mynginx:${{ github.sha }} .
          docker tag mynginx:${{ github.sha }} mynginx:latest

      - name: Deploy
        run: |
          kubectl set image deployment/my-nginx \
          my-nginx=mynginx:${{ github.sha }}

          kubectl rollout status deployment/my-nginx
