- name: Build
  run: |
    docker build -t 192.168.178.115:5000/mynginx:${{ github.sha }} .

- name: Push
  run: |
    docker push 192.168.178.115:5000/mynginx:${{ github.sha }}

- name: Deploy
  run: |
    kubectl set image deployment/my-nginx \
      my-nginx=192.168.178.115:5000/mynginx:${{ github.sha }}

- name: Verify
  run: |
    kubectl rollout status deployment/my-nginx
